layout_spectrum: 0.04155858885496855
typography_spectrum: 0.2952333989087492
color:
  brandStrength: 0.9551631927024573
  lightness: 0.5153853890951723
  saturation: 0.579680360853672
  rhythmicContrast: 0.5222479398362339
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
name: Aurelius
